export const DEFAULT_EDITOR_STATE = {
	screen_height: 0,
	screen_width: 0,
	initialized: false,
	active_profile: undefined,
};

// Root Keys
export enum ROOT_KEYS {
	ResolutionSizeY = "ResolutionSizeY",
	ResolutionSizeX = "ResolutionSizeX",
	HUDSettingsProfile = "HUDSettingsProfile",
	HeroSelectedHUDProfile = "HeroSelectedHUDProfile",
	HeroAbilityMapping = "HeroAbilityMapping",
	DamageMeterSettings = "DamageMeterSettings",
}

export enum PROFILE_KEYS {
	ProfileName = "ProfileName",
	PartyFrameGrowthDirection = "PartyFrameGrowthDirection",
	PartyFrameSpacing = "PartyFrameSpacing",
	SnapGridSize = "SnapGridSize",
	PartyUnitFrameBuffPlacement = "PartyUnitFrameBuffPlacement",
	PartyUnitFrameShowPercent = "PartyUnitFrameShowPercent",
	PartyUnitFrameShowRole = "PartyUnitFrameShowRole",
	ElementCanvasPositions = "ElementCanvasPositions",
	AbilityBarShowBackground = "AbilityBarShowBackground",
	DamageMeterShowMeter1 = "DamageMeterShowMeter1",
	DamageMeterShowMeter2 = "DamageMeterShowMeter2",
	DamageMeterUseLargeText = "DamageMeterUseLargeText",
	DamageMeterWindowWidth = "DamageMeterWindowWidth",
	DungeonInfoUseMinimalVersion = "DungeonInfoUseMinimalVersion",
	DungeonInfoShowCurses = "DungeonInfoShowCurses",
	DungeonInfoShowAscensions = "DungeonInfoShowAscensions",
	DungeonInfoShowBossProgress = "DungeonInfoShowBossProgress",
	TargetUnitFrameShowIcon = "TargetUnitFrameShowIcon",
	TargetUnitFrameAlwaysShowHealthText = "TargetUnitFrameAlwaysShowHealthText",
	TargetUnitFrameMinimalFrameMode = "TargetUnitFrameMinimalFrameMode",
	TargetUnitFrameLargeNameText = "TargetUnitFrameLargeNameText",
	TargetUnitFrameShowCastbar = "TargetUnitFrameShowCastbar",
	TargetUnitFrameScale = "TargetUnitFrameScale",
	TargetUnitFrameWidth = "TargetUnitFrameWidth",
	TargetOfTargetShow = "TargetOfTargetShow",
	TargetOfTargetShowIcon = "TargetOfTargetShowIcon",
	TargetOfTargetMinimalFrameMode = "TargetOfTargetMinimalFrameMode",
	TargetOfTargetScale = "TargetOfTargetScale",
	TargetOfTargetWidth = "TargetOfTargetWidth",
	SelfUnitFrameShowIcon = "SelfUnitFrameShowIcon",
	SelfUnitFrameShowName = "SelfUnitFrameShowName",
	SelfUnitFrameAlwaysShowHealthNumbers = "SelfUnitFrameAlwaysShowHealthNumbers",
	SelfUnitFrameMinimalFrameMode = "SelfUnitFrameMinimalFrameMode",
	SelfUnitFrameLargeNameText = "SelfUnitFrameLargeNameText",
	SelfUnitFrameShowRoleIcon = "SelfUnitFrameShowRoleIcon",
	SelfUnitFrameScale = "SelfUnitFrameScale",
	SelfUnitFrameWidth = "SelfUnitFrameWidth",
	AbilityBarSettings = "AbilityBarSettings",
	HeroHUDPrimaryAngle = "HeroHUDPrimaryAngle",
	HeroHUDSecondaryAngle = "HeroHUDSecondaryAngle",
	HeroHUDTertiaryAngle = "HeroHUDTertiaryAngle",
	HeroHUDPrimaryScale = "HeroHUDPrimaryScale",
	HeroHUDSecondaryScale = "HeroHUDSecondaryScale",
	HeroHUDSecondaryScaleY = "HeroHUDSecondaryScaleY",
	HeroHUDTertiaryScale = "HeroHUDTertiaryScale",
	EnemyTooltipEnabled = "EnemyTooltipEnabled",
	SelfBuffsExtraScale = "SelfBuffsExtraScale",
	SelfDebuffsExtraScale = "SelfDebuffsExtraScale",
	SelfBuffGrowDirection = "SelfBuffGrowDirection",
	SelfDebuffGrowDirection = "SelfDebuffGrowDirection",
	HeroBuffbarExtraScale = "HeroBuffbarExtraScale",
	HeroBuffbarGrowDirection = "HeroBuffbarGrowDirection",
}
